[project]
name = "rprover"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "datasets>=4.2.0",
    "litellm>=1.78.5",
    "tqdm>=4.66.0",
]
